DROP TABLE IF EXISTS t4_outbox;
DROP TABLE IF EXISTS t4_owner_leases;
DROP TABLE IF EXISTS t4_snapshot_entries;
DROP TABLE IF EXISTS t4_event_retention;
DROP TABLE IF EXISTS t4_events;
DROP TABLE IF EXISTS t4_session_intents;
DROP TABLE IF EXISTS t4_workspace_intents;
DROP TABLE IF EXISTS t4_commands;
DROP TABLE IF EXISTS t4_schema_migrations;
