apiVersion: v1
kind: Service
metadata:
  name: {{ include "t4-site.fullname" . | quote }}
  labels:
    {{- include "t4-site.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "t4-site.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
